!!****m* ABINIT/interfaces_01_interfaces_ext
!! NAME
!! interfaces_01_interfaces_ext
!!
!! FUNCTION
!! This module contains the interfaces of the routines
!! in the directory 01_interfaces_ext
!!
!! COPYRIGHT
!! Copyright (C) 2010-2018 ABINIT group
!! This file is distributed under the terms of the
!! GNU General Public License, see ~abinit/COPYING
!! or http://www.gnu.org/copyleft/gpl.txt .
!!
!! NOTES
!! THIS FILE IS GENERATED AUTOMATICALLY BY abilint.
!! To do that: config/scripts/abilint . .
!!
!!
!! WARNING
!! No interface generated by abilint
!! Please, correct the following problem in the code:
!!   
!!   Arguments of the routine 'dmfet_subspac': 'dtset' 'psps'
!!   ==Code==================================================>
!!    type(dmfet_type), intent(inout) :: this
!!    type(dataset_type),intent(in),target :: dtset
!!   
!!    type(crystal_t) :: crystal
!!    type(plowannier_type) :: wan
!!   
!!    integer :: timrev
!!    logical :: remove_inv
!!   
!!    !Crystalline structure.
!!   ========================================================<
!!   [./src/95_drive/m_dmfet.F90:dmfet_subspac] Argument {psps} is not declared
!!
!! SOURCE

#if defined HAVE_CONFIG_H
#include "config.h"
#endif

module interfaces_01_interfaces_ext

 implicit none

end module interfaces_01_interfaces_ext
!!***
