#
# Config file generated by Abinit
#
# NOTE: You may adjust it before running 'configure'.
#

# Abinit paths
with_abinit_builddir="/tigress/xingz/abinit-8.10.2"
with_abinit_srcdir="/tigress/xingz/abinit-8.10.2"

# C support
CPP="mpiicc -E"
CPPFLAGS=""
CC="mpiicc"
CFLAGS=" -g -O2 -vec-report0 "
CC_LDFLAGS="   -static-libgcc -static-intel "

# C++ support
XPP=""
XPPFLAGS="    "
CXX="mpiicpc"
CXXFLAGS=" -g -O2 -mtune=native -march=native  "
CXX_LDFLAGS="    "

# Fortran support
FPP=""
FPPFLAGS="    "
FC="mpiifort"
FCFLAGS=" -g -extend-source -noaltparam -nofpscomp   -O3"
FC_LDFLAGS="   -static-intel -static-libgcc "
with_fc_vendor="intel"
with_fc_version="18.0"

# Python support
PYTHON="python"
PYFLAGS=""
PYTHON_CPPFLAGS="-I/usr/licensed/anaconda/5.0.1/include/python2.7 -I/home/xingz/.local/lib/python2.7/site-packages/numpy/core/include"

# Utilities
AR="ar"
ARFLAGS="     rc"
RANLIB="ranlib"

# Parallel I/O use flags
lib_etsf_io_incs=""
lib_etsf_io_libs=""
lib_netcdf_incs=""
lib_netcdf_libs=""

# Linear algebra use flags
lib_linalg_fcflags=""
lib_linalg_ldflags=""
lib_linalg_incs=""
lib_linalg_libs="-lmkl_intel_lp64  -lmkl_intel_lp64 -L/opt/intel/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64 -lmkl_sequential -lmkl_core -lpthread -lm "

# FFT use flags
lib_fft_incs=""
lib_fft_libs="-lfftw3"

# Feature triggers use flags
lib_bigdft_incs=""
lib_bigdft_libs=""
lib_gsl_incs="@lib_gsl_incs@"
lib_gsl_libs="@lib_gsl_libs@"
lib_levmar_incs="@lib_levmar_incs@"
lib_levmar_libs="@lib_levmar_libs@"
lib_libxc_incs="-I$(fallbacks_instdir)/include"
lib_libxc_libs="-L$(fallbacks_instdir)/lib -lxcf90 -lxc"
lib_papi_incs="@lib_papi_incs@"
lib_papi_libs="@lib_papi_libs@"
lib_triqs_incs=""
lib_triqs_libs=""
lib_wannier90_bins=""
lib_wannier90_incs=""
lib_wannier90_libs=""
lib_yaml_incs=""
lib_yaml_libs=""
